INSERT  INTO Estado (_id,nome,sigla) values(1,"Minas Gerais","MG");
INSERT  INTO Estado (_id,nome,sigla) values(2,"São Paulo","SP");
INSERT  INTO Estado (_id,nome,sigla) values(3,"Rio Grande do Sul","RS");
INSERT  INTO Estado (_id,nome,sigla) values(4,"Bahia","BH");
INSERT  INTO Estado (_id,nome,sigla) values(5,"Paraná","PR");
INSERT  INTO Estado (_id,nome,sigla) values(6,"Santa Catarina","SC");
INSERT  INTO Estado (_id,nome,sigla) values(7,"Goiás","GO");
INSERT  INTO Estado (_id,nome,sigla) values(8,"Piauí","PI");
INSERT  INTO Estado (_id,nome,sigla) values(9,"Paraíba","PB");
INSERT  INTO Estado (_id,nome,sigla) values(10,"Maranhão","MA");
INSERT  INTO Estado (_id,nome,sigla) values(11,"Pernambuco","PE");
INSERT  INTO Estado (_id,nome,sigla) values(12,"Ceará","CE");
INSERT  INTO Estado (_id,nome,sigla) values(13,"Rio Grande do Norte","RN");
INSERT  INTO Estado (_id,nome,sigla) values(14,"Pará","PA");
INSERT  INTO Estado (_id,nome,sigla) values(15,"Mato Grosso","MT");
INSERT  INTO Estado (_id,nome,sigla) values(16,"Tocantins","TO");
INSERT  INTO Estado (_id,nome,sigla) values(17,"Alagoas","AL");
INSERT  INTO Estado (_id,nome,sigla) values(18,"Rio de Janeiro","RJ");
INSERT  INTO Estado (_id,nome,sigla) values(19,"Mato Grosso do Sul","MS");
INSERT  INTO Estado (_id,nome,sigla) values(20,"Espírito Santo","ES");
INSERT  INTO Estado (_id,nome,sigla) values(21,"Sergipe","SE");
INSERT  INTO Estado (_id,nome,sigla) values(22,"Amazonas","AM");
INSERT  INTO Estado (_id,nome,sigla) values(23,"Rondônia","RO");
INSERT  INTO Estado (_id,nome,sigla) values(24,"Acre","AC");
INSERT  INTO Estado (_id,nome,sigla) values(25,"Amapá","AP");
INSERT  INTO Estado (_id,nome,sigla) values(26,"Roraima","RR");

INSERT  INTO Cidade (_id,nome,id_Estado) values(1,"Barracão",5);
INSERT  INTO Cidade (_id,nome,id_Estado) values(2,"São Miguel do Oeste",6);
